### ISSUE TITLE
Pagination feature request

### ISSUE THREAD

**Issue by Jajasoso** [codedbycurtis/soundcloud_explode_dart#3]
Hello, 
Thank you for creating the library. I was wondering how to handle pagination? If I don't specify the limit parameter and there are a lot of results how do we handle the pagination? If not yet possible, could you add that functionality, please? Thank you!

**Comment by codedbycurtis** [comment]
Hi @Jajasoso, thank you for using the library.

Each of the search functions (I'll use `getTracks` in this example) returns a stream containing batches of results (`Stream<Iterable<TrackSearchResult>>`). The limit parameter specifies how many results each batch should contain, which in your case means how many results each page should contain. The default is 10 if left unspecified.

Below is a short example of pagination:
```dart
import 'dart:async';

final client = SoundcloudClient();

// Limit can be specified here to show more or less results per page.
final stream = client.search.getTracks('my search query', limit: 50);

// This is used to iterate through the pages, so we don't fetch thousands of tracks at once.
final iterator = StreamIterator(stream);

// Attempts to get the first page, then the second, then the third, etc.,
// returning true if there is another page; otherwise, false.
while (await iterator.moveNext()) {
    // Iterate through each of our 50 returned tracks and do something with them.
    for (final track in iterator.current) {
        print(track.title);
    }
}
```

If you are using Flutter, things would be slightly different as you would instead wait until the user scrolled a certain amount down the page before calling `await iterator.moveNext()`, rather than using it in a `while` loop, but the principle is still the same.

Let me know if you need any more help; otherwise, feel free to close this issue.

**Comment by Jajasoso** [comment]
Thank you for your reply. It works just as you pointed out. Much
appreciated.
